### ISSUE TITLE
Missing route/module error

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/polydev#8]
When working on #5, I saw that this error doesn't bubble up to the UI:

```
(node:45054) UnhandledPromiseRejectionWarning: Error: Cannot find module 'react-app'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.<anonymous> (/Users/eric/Projects/ericclemmons/polydev/routes/react-app/index.js:3:26)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object._extensions.(anonymous function) [as .js] (/Users/eric/Projects/ericclemmons/polydev/node_modules/hot-module-replacement/index.js:15:33)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module._load (/Users/eric/Projects/ericclemmons/polydev/node_modules/hot-module-replacement/index.js:132:12)
(node:45054) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:45054) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by ericclemmons** [comment]
4039216
